import doctors from "@/data/doctors.json";

/**
 * Nearest-doctor lookup over the geocoded doctor list (src/data/doctors.json,
 * generated by scripts/build-doctors.mjs). Server-only, no dependencies.
 *
 * DATA CAVEAT: many doctors share a city-centroid coordinate (Nominatim
 * geocoded to the city, not the clinic). So "nearest" is effectively
 * city-level, not street-level — surface distances as approximate.
 */

const R_KM = 6371;
const toRad = (deg) => (deg * Math.PI) / 180;

/** Great-circle distance in km between two lat/lng points. */
export function haversineKm(lat1, lng1, lat2, lng2) {
  const dLat = toRad(lat2 - lat1);
  const dLng = toRad(lng2 - lng1);
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLng / 2) ** 2;
  return R_KM * 2 * Math.asin(Math.sqrt(a));
}

const round1 = (n) => Math.round(n * 10) / 10;

// Doctors within this many km of each other are treated as the same spot for
// tie-breaking — the geocoder collapses a whole city onto one centroid, so
// dozens of clinics land at *exactly* 0 km apart. Kept to ~10 m (just above
// float noise) so distance always wins: a genuinely closer doctor is shown
// even when it has no phone — the UI falls back to its address in that case.
const TIE_KM = 0.01;

// Contactability score: a card with a phone (the "Call" CTA) beats one with
// just an address, which beats a bare name. Used only to break distance ties.
const quality = (d) =>
  (d.phone ? 4 : 0) + (d.address ? 2 : 0) + (d.pincode ? 1 : 0);

/**
 * The single closest doctor to (lat, lng), with `distance_km` attached.
 * Returns null only if the dataset is empty.
 *
 * When several doctors sit at effectively the same distance (see DATA CAVEAT —
 * city-centroid coordinates make this the common case), the one with the most
 * complete contact info wins instead of whichever happened to be first in the
 * list.
 */
export function findNearest(lat, lng) {
  let best = null;
  let bestKm = Infinity;
  let bestQuality = -1;
  for (const d of doctors) {
    const km = haversineKm(lat, lng, d.lat, d.lng);
    if (km < bestKm - TIE_KM) {
      // Clearly closer — take it regardless of data quality.
      bestKm = km;
      bestQuality = quality(d);
      best = d;
    } else if (km <= bestKm + TIE_KM) {
      // Same spot: keep the better-documented doctor, and track the true
      // minimum distance so later comparisons stay honest.
      const q = quality(d);
      if (q > bestQuality) {
        bestQuality = q;
        best = d;
      }
      if (km < bestKm) bestKm = km;
    }
  }
  return best ? { ...best, distance_km: round1(bestKm) } : null;
}

/**
 * Distinct cities with a representative coordinate, for the manual fallback
 * (city <select>) when the browser can't/won't share a location. Sorted by
 * city name.
 */
export function listCities() {
  const seen = new Map();
  for (const d of doctors) {
    if (!d.city || seen.has(d.city)) continue;
    seen.set(d.city, { city: d.city, state: d.state, lat: d.lat, lng: d.lng });
  }
  return [...seen.values()].sort((a, b) => a.city.localeCompare(b.city));
}

// --- City canonicalization --------------------------------------------------
// The dataset stores one spelling per city ("Bengaluru", "Gurgaon", "NOIDA").
// Visitors type variants and typos ("bangalore", "gurugram", "gaziabad"). We
// resolve any input to the exact spelling present in the data, so pincode/city
// matching is reliable and the returned doctor.city is always consistent.

const normalize = (s) =>
  (s ?? "")
    .toString()
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ") // punctuation → space
    .replace(/\s+/g, " ")
    .trim();

// Distinct city spellings actually present in the data, computed once.
const CANONICAL_CITIES = [...new Set(doctors.map((d) => d.city).filter(Boolean))];

// Hand-maintained aliases for names too far apart for edit-distance to catch
// safely (Bengaluru/Bangalore, Gurgaon/Gurugram, …). Keys are normalized;
// every value must be one of CANONICAL_CITIES.
const CITY_ALIASES = {
  bangalore: "Bengaluru",
  banglore: "Bengaluru",
  bengalooru: "Bengaluru",
  bengaluru: "Bengaluru",
  blr: "Bengaluru",
  gurugram: "Gurgaon",
  "new delhi": "Delhi",
  "greater noida": "NOIDA",
  gaziabad: "Ghaziabad",
  hydrabad: "Hyderabad",
  bhubaneshwar: "Bhubaneswar",
  bhubneswar: "Bhubaneswar",
  chd: "Chandigarh",
};

/** Levenshtein edit distance (small strings, two-row DP). */
function editDistance(a, b) {
  const m = a.length;
  const n = b.length;
  if (!m) return n;
  if (!n) return m;
  let prev = Array.from({ length: n + 1 }, (_, j) => j);
  let curr = new Array(n + 1);
  for (let i = 1; i <= m; i++) {
    curr[0] = i;
    for (let j = 1; j <= n; j++) {
      const cost = a[i - 1] === b[j - 1] ? 0 : 1;
      curr[j] = Math.min(prev[j] + 1, curr[j - 1] + 1, prev[j - 1] + cost);
    }
    [prev, curr] = [curr, prev];
  }
  return prev[n];
}

/**
 * Resolve a free-text city string to the exact spelling used in the data, or
 * null if it doesn't plausibly name one of our cities.
 *   1. exact (normalized) match, e.g. "noida" → "NOIDA"
 *   2. alias table, e.g. "bangalore" → "Bengaluru", "gurugram" → "Gurgaon"
 *   3. fuzzy: closest canonical city within 2 edits (catches typos like
 *      "gaziabad" → "Ghaziabad"); a genuinely different city (Mumbai, Pune)
 *      exceeds the threshold and returns null.
 */
export function canonicalCity(input) {
  const q = normalize(input);
  if (!q) return null;

  const direct =
    CANONICAL_CITIES.find((c) => normalize(c) === q) || CITY_ALIASES[q];
  if (direct) return direct;

  let best = null;
  let bestD = Infinity;
  for (const c of CANONICAL_CITIES) {
    const d = editDistance(q, normalize(c));
    if (d < bestD) {
      bestD = d;
      best = c;
    }
  }
  // Short names get a stricter budget so unrelated short cities ("Goa", "Pune")
  // don't collapse onto a similar-looking one; longer names tolerate 2 typos.
  const maxDist = q.length <= 4 ? 1 : 2;
  return bestD <= maxDist ? best : null;
}

/**
 * Resolve a doctor by (free-text) name. Used by the appointment-notify flow to
 * find the doctor's phone number from the name the user picked.
 *   1. exact normalized match ("dr. sheetal jindal" === "Dr. Sheetal Jindal")
 *   2. substring match either way ("sheetal jindal" ⊂ "dr. sheetal jindal")
 *   3. fuzzy: closest name within an edit budget that scales with length
 * Optionally constrained to a city so two doctors sharing a name in different
 * cities resolve to the right one. Returns the raw doctor record or null.
 */
export function findByName(name, city) {
  const q = normalize(name);
  if (!q) return null;

  // Narrow to the city first when given and it resolves to one we cover.
  const canon = city ? canonicalCity(city) : null;
  const pool = canon ? doctors.filter((d) => d.city === canon) : doctors;
  const searchPool = pool.length ? pool : doctors;

  // 1. exact normalized match.
  const exact = searchPool.find((d) => normalize(d.name) === q);
  if (exact) return exact;

  // 2. substring match (handles missing/extra "Dr." prefix, partial names).
  const sub = searchPool.find((d) => {
    const dn = normalize(d.name);
    return dn.includes(q) || q.includes(dn);
  });
  if (sub) return sub;

  // 3. fuzzy: closest name within a length-scaled edit budget.
  let best = null;
  let bestD = Infinity;
  for (const d of searchPool) {
    const dist = editDistance(q, normalize(d.name));
    if (dist < bestD) {
      bestD = dist;
      best = d;
    }
  }
  const maxDist = Math.max(2, Math.floor(q.length / 4));
  return bestD <= maxDist ? best : null;
}

/** Length of the shared leading-digit run of two pincode strings. */
const sharedPrefixLen = (a, b) => {
  let i = 0;
  while (i < a.length && i < b.length && a[i] === b[i]) i++;
  return i;
};

/**
 * Nearest doctors by pincode when there's no exact hit: those whose pincode
 * shares the longest leading-digit run with `pincode`. Requires ≥3 shared
 * digits (same postal sorting district ≈ genuinely nearby) — so a pincode from
 * a region with no doctors (Mumbai 400xxx shares nothing with our cities)
 * returns null instead of a far-away false match. Constrained to `city` when
 * given and that narrows the group.
 */
function nearestByPincodePrefix(pincode, city) {
  const pool = doctors.filter((d) => d.pincode);
  let bestLen = 0;
  for (const d of pool) {
    const len = sharedPrefixLen(pincode, d.pincode);
    if (len > bestLen) bestLen = len;
  }
  if (bestLen < 3) return null;

  let group = pool.filter((d) => sharedPrefixLen(pincode, d.pincode) === bestLen);
  if (city) {
    const inCity = group.filter((d) => d.city === city);
    if (inCity.length) group = inCity;
  }
  return pickBest(group);
}

/**
 * Find the best doctor matching a free-text location string that may contain a
 * city name, a 6-digit pincode, or both (in any order, comma/space separated).
 *
 * Matching priority:
 *   1. **Exact pincode** — most specific; refined to the resolved city when one
 *      is also given and agrees.
 *   2. **Nearby pincode** — same postal district (≥3 shared leading digits)
 *      when no exact pincode hit; refined by city when given.
 *   3. **Canonical city** — the input city resolved to its exact data spelling
 *      (aliases + typo-tolerant), when there's no usable pincode.
 * Among the matches, the doctor with the best contact-info quality wins.
 *
 * Returns `{ ...doctor, distance_km: 0 }` (matched by area, not coordinates) or
 * `null` when the location names no city/district we cover (caller → 404).
 *
 * Examples of accepted input:
 *   "Bangalore"       →  alias → Bengaluru doctor
 *   "gaziabad"        →  typo → Ghaziabad doctor
 *   "Delhi 110009"    →  exact pincode, city agrees
 *   "560099"          →  no exact hit → nearest Bengaluru (560xxx) doctor
 *   "Mumbai 400001"   →  unknown city + unknown district → null → 404
 */
export function findByLocation(location) {
  const input = (location ?? "").trim();
  if (!input) return null;

  // Extract a 6-digit Indian pincode (if present).
  const pincodeMatch = input.match(/\b(\d{6})\b/);
  const pincode = pincodeMatch ? pincodeMatch[1] : null;

  // Everything that isn't the pincode is the city string → resolve to the exact
  // spelling in the data (fixes "bangalore" → "Bengaluru", typos, etc.).
  const cityRaw = input.replace(/\b\d{6}\b/, " ").replace(/[,]/g, " ");
  const city = canonicalCity(cityRaw);

  // --- 1. Pincode (most specific) ---
  if (pincode) {
    // 1a. Exact 6-digit pincode; refine to the city when it agrees.
    const exact = doctors.filter((d) => d.pincode === pincode);
    if (exact.length) {
      const inCity = city ? exact.filter((d) => d.city === city) : [];
      return pickBest(inCity.length ? inCity : exact);
    }

    // 1b. No exact hit → nearest doctor in the same postal district.
    const nearby = nearestByPincodePrefix(pincode, city);
    if (nearby) return nearby;
  }

  // --- 2. Canonical city ---
  if (city) {
    const cityHits = doctors.filter((d) => d.city === city);
    if (cityHits.length > 0) return pickBest(cityHits);
  }

  return null;
}

/**
 * From a list of matched doctors, pick the one with the best contact-info
 * quality (phone > address > pincode). Returns the doctor with distance_km: 0
 * since we matched by location name, not coordinates.
 */
function pickBest(matches) {
  let best = matches[0];
  let bestQ = quality(best);
  for (let i = 1; i < matches.length; i++) {
    const q = quality(matches[i]);
    if (q > bestQ) {
      bestQ = q;
      best = matches[i];
    }
  }
  return { ...best, distance_km: 0 };
}
