import doctors from "@/data/doctors.json";

/**
 * Nearest-doctor lookup over the geocoded doctor list (src/data/doctors.json,
 * generated by scripts/build-doctors.mjs). Server-only, no dependencies.
 *
 * DATA CAVEAT: many doctors share a city-centroid coordinate (Nominatim
 * geocoded to the city, not the clinic). So "nearest" is effectively
 * city-level, not street-level — surface distances as approximate.
 */

const R_KM = 6371;
const toRad = (deg) => (deg * Math.PI) / 180;

/** Great-circle distance in km between two lat/lng points. */
export function haversineKm(lat1, lng1, lat2, lng2) {
  const dLat = toRad(lat2 - lat1);
  const dLng = toRad(lng2 - lng1);
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLng / 2) ** 2;
  return R_KM * 2 * Math.asin(Math.sqrt(a));
}

const round1 = (n) => Math.round(n * 10) / 10;

// Doctors within this many km of each other are treated as the same spot for
// tie-breaking — the geocoder collapses a whole city onto one centroid, so
// dozens of clinics land at *exactly* 0 km apart. Kept to ~10 m (just above
// float noise) so distance always wins: a genuinely closer doctor is shown
// even when it has no phone — the UI falls back to its address in that case.
const TIE_KM = 0.01;

// Contactability score: a card with a phone (the "Call" CTA) beats one with
// just an address, which beats a bare name. Used only to break distance ties.
const quality = (d) =>
  (d.phone ? 4 : 0) + (d.address ? 2 : 0) + (d.pincode ? 1 : 0);

/**
 * The single closest doctor to (lat, lng), with `distance_km` attached.
 * Returns null only if the dataset is empty.
 *
 * When several doctors sit at effectively the same distance (see DATA CAVEAT —
 * city-centroid coordinates make this the common case), the one with the most
 * complete contact info wins instead of whichever happened to be first in the
 * list.
 */
export function findNearest(lat, lng) {
  let best = null;
  let bestKm = Infinity;
  let bestQuality = -1;
  for (const d of doctors) {
    const km = haversineKm(lat, lng, d.lat, d.lng);
    if (km < bestKm - TIE_KM) {
      // Clearly closer — take it regardless of data quality.
      bestKm = km;
      bestQuality = quality(d);
      best = d;
    } else if (km <= bestKm + TIE_KM) {
      // Same spot: keep the better-documented doctor, and track the true
      // minimum distance so later comparisons stay honest.
      const q = quality(d);
      if (q > bestQuality) {
        bestQuality = q;
        best = d;
      }
      if (km < bestKm) bestKm = km;
    }
  }
  return best ? { ...best, distance_km: round1(bestKm) } : null;
}

/**
 * Distinct cities with a representative coordinate, for the manual fallback
 * (city <select>) when the browser can't/won't share a location. Sorted by
 * city name.
 */
export function listCities() {
  const seen = new Map();
  for (const d of doctors) {
    if (!d.city || seen.has(d.city)) continue;
    seen.set(d.city, { city: d.city, state: d.state, lat: d.lat, lng: d.lng });
  }
  return [...seen.values()].sort((a, b) => a.city.localeCompare(b.city));
}

/**
 * Find the best doctor matching a free-text location string that may contain a
 * city name, a 6-digit pincode, or both (in any order, comma/space separated).
 *
 * Matching priority:
 *   1. **Exact pincode** — most specific; if a 6-digit Indian pincode is found
 *      in the string, doctors with that pincode are matched first.
 *   2. **City name** (case-insensitive) — fallback when no pincode is present
 *      or no doctors have that pincode.
 *   3. Among all matches, the doctor with the best contact-info quality wins
 *      (same scoring as findNearest).
 *
 * Returns `{ ...doctor, distance_km: 0 }` or `null`.
 *
 * Examples of accepted input:
 *   "Delhi 110009"  →  pincode match first, city refines
 *   "110009"        →  pincode match
 *   "Agra"          →  city match
 *   "agra, 282001"  →  pincode match within Agra
 */
export function findByLocation(location) {
  const input = location.trim();
  if (!input) return null;

  // Extract a 6-digit Indian pincode (if present).
  const pincodeMatch = input.match(/\b(\d{6})\b/);
  const pincode = pincodeMatch ? pincodeMatch[1] : null;

  // Extract city: strip the pincode (if any), commas, extra spaces → whatever
  // remains is treated as the city name.
  const cityRaw = input
    .replace(/\b\d{6}\b/, "")   // remove pincode
    .replace(/[,]/g, " ")       // commas → spaces
    .replace(/\s+/g, " ")       // collapse whitespace
    .trim()
    .toLowerCase();

  // --- 1. Pincode match (most specific) ---
  if (pincode) {
    const pincodeHits = doctors.filter((d) => d.pincode === pincode);

    // If we also have a city string, narrow within pincode hits.
    if (pincodeHits.length > 0 && cityRaw) {
      const refined = pincodeHits.filter(
        (d) => d.city && d.city.toLowerCase() === cityRaw
      );
      if (refined.length > 0) return pickBest(refined);
    }

    if (pincodeHits.length > 0) return pickBest(pincodeHits);
  }

  // --- 2. City name match (case-insensitive) ---
  if (cityRaw) {
    const cityHits = doctors.filter(
      (d) => d.city && d.city.toLowerCase() === cityRaw
    );
    if (cityHits.length > 0) return pickBest(cityHits);

    // Partial / fuzzy: city name *contains* the input or input contains the
    // city name (handles "New Delhi" → "Delhi", "Noida" → "NOIDA", etc.)
    const partialHits = doctors.filter(
      (d) =>
        d.city &&
        (d.city.toLowerCase().includes(cityRaw) ||
          cityRaw.includes(d.city.toLowerCase()))
    );
    if (partialHits.length > 0) return pickBest(partialHits);
  }

  return null;
}

/**
 * From a list of matched doctors, pick the one with the best contact-info
 * quality (phone > address > pincode). Returns the doctor with distance_km: 0
 * since we matched by location name, not coordinates.
 */
function pickBest(matches) {
  let best = matches[0];
  let bestQ = quality(best);
  for (let i = 1; i < matches.length; i++) {
    const q = quality(matches[i]);
    if (q > bestQ) {
      bestQ = q;
      best = matches[i];
    }
  }
  return { ...best, distance_km: 0 };
}
